# Generated by Django 5.0.6 on 2024-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('mpg', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('doors', models.IntegerField()),
                ('submodel', models.CharField(max_length=255)),
                ('msrp', models.FloatField()),
                ('rating', models.CharField(max_length=1)),
                ('consumer_rating', models.FloatField()),
                ('photo', models.URLField()),
            ],
        ),
    ]
